spring.application.name=velora-backend

server.port=${PORT:8080}
server.servlet.context-path=

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://avnadmin:TU_PASSWORD@pg-bridget-bridmen18-8fa7.g.aivencloud.com:18814/defaultdb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

logging.level.root=INFO
